apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: xxx.xxx.xxx.xxx:5000/mynginx:1.0
        ports:
        - containerPort: 80
      - name: phpfpm
        image: xxx.xxx.xxx.xxx:5000/myphpfpm:1.0
        ports:
        - containerPort: 9000
